CREATE TABLE users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username varchar(50) NOT NULL UNIQUE,
 email varchar(100) NOT NULL UNIQUE,
 password varchar(255) NOT NULL,
 full_name varchar(100), phone varchar(20), avatar varchar(255),
 status varchar(20) NOT NULL DEFAULT 'ACTIVE',
 created_at timestamp NOT NULL, updated_at timestamp
);
CREATE TABLE movies (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title varchar(255) NOT NULL, description text, duration int NOT NULL,
 release_date date, director varchar(255), age_rating varchar(20),
 poster_url varchar(500), trailer_url varchar(500),
 status varchar(20) NOT NULL DEFAULT 'ACTIVE',
 created_at timestamp, updated_at timestamp
);
CREATE TABLE cinemas (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(255) NOT NULL, address varchar(500), city varchar(100), phone varchar(20),
 status varchar(20) NOT NULL DEFAULT 'ACTIVE', created_at timestamp
);
CREATE TABLE rooms (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cinema_id bigint NOT NULL REFERENCES cinemas(id),
 name varchar(100) NOT NULL, capacity int NOT NULL, room_type varchar(30),
 status varchar(20) NOT NULL DEFAULT 'ACTIVE'
);
CREATE TABLE showtimes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 movie_id bigint NOT NULL REFERENCES movies(id),
 room_id bigint NOT NULL REFERENCES rooms(id),
 start_time timestamp NOT NULL, end_time timestamp NOT NULL,
 price decimal(12,2) NOT NULL,
 status varchar(20) NOT NULL DEFAULT 'AVAILABLE', created_at timestamp
);
CREATE TABLE seats (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 room_id bigint NOT NULL REFERENCES rooms(id),
 seat_number varchar(10) NOT NULL, row_name varchar(5), seat_type varchar(30),
 status varchar(20) NOT NULL DEFAULT 'ACTIVE'
);
CREATE TABLE bookings (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id),
 booking_code varchar(50) NOT NULL UNIQUE, total_amount decimal(12,2) NOT NULL,
 status varchar(30) NOT NULL DEFAULT 'PENDING', expires_at timestamp,
 created_at timestamp, updated_at timestamp
);
CREATE TABLE combos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(255) NOT NULL, description text, price decimal(12,2) NOT NULL,
 image_url varchar(500), status varchar(20) NOT NULL DEFAULT 'ACTIVE',
 created_at timestamp, updated_at timestamp
);
CREATE TABLE booking_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id bigint NOT NULL REFERENCES bookings(id),

    showtime_id bigint REFERENCES showtimes(id),
    seat_id bigint REFERENCES seats(id),
    combo_id bigint REFERENCES combos(id),

    quantity int NOT NULL DEFAULT 1,
    price decimal(12,2) NOT NULL,
    total_price decimal(12,2) NOT NULL,

    status varchar(20) NOT NULL DEFAULT 'RESERVED',

    created_at timestamp,
    updated_at timestamp
);
CREATE TABLE payment_methods (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(50) NOT NULL UNIQUE, display_name varchar(100), provider_code varchar(50),
 api_url varchar(255), webhook_url varchar(255),
 status varchar(20) NOT NULL DEFAULT 'ACTIVE', created_at timestamp, updated_at timestamp
);
CREATE TABLE invoices (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id),
 booking_id bigint NOT NULL UNIQUE REFERENCES bookings(id),
 invoice_number varchar(50) NOT NULL UNIQUE,
 -- Many invoices may use the same payment method.
 payment_method_id bigint NOT NULL REFERENCES payment_methods(id),
 subtotal decimal(12,2) NOT NULL,
 discount_amount decimal(12,2) NOT NULL DEFAULT 0,
 tax_amount decimal(12,2) NOT NULL DEFAULT 0,
 total_amount decimal(12,2) NOT NULL,
 status varchar(20) NOT NULL DEFAULT 'UNPAID', issued_at timestamp, due_at timestamp,
 created_at timestamp NOT NULL, updated_at timestamp
);
CREATE TABLE email_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name varchar(100) NOT NULL UNIQUE,
    subject varchar(255) NOT NULL,

    -- Nội dung email, có thể chứa placeholder:
    -- {{username}}, {{booking_code}}, {{total_amount}}, ...
    body text NOT NULL,

    -- Ví dụ: BOOKING_CONFIRMATION, PASSWORD_RESET, EMAIL_VERIFICATION
    type varchar(50) NOT NULL UNIQUE,

    status varchar(20) NOT NULL DEFAULT 'ACTIVE',

    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp
);
-- Run as movie_app (or SET ROLE movie_app) in movie_booking.
CREATE TABLE IF NOT EXISTS user_registration_outbox (
    event_id varchar(36) PRIMARY KEY,
    user_id bigint NOT NULL,
    username varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_registration_outbox_pending
    ON user_registration_outbox (created_at, event_id);
