spring.application.name=user-service
server.port=${SERVER_PORT:8081}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:movie_booking}
spring.datasource.username=${DB_USER:movie_app}
spring.datasource.password=${APP_DB_PASSWORD}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
